<div>
    <div class="mb-6"><h1 class="text-2xl font-bold text-slate-900">Caja</h1><p class="text-sm text-slate-500">{{ $register?->name ?? 'Sin caja activa' }}</p></div>
    @if(session('success'))<div class="mb-4 rounded-lg bg-emerald-50 p-3 text-sm text-emerald-700">{{ session('success') }}</div>@endif
    @if(! $session)
        <div class="max-w-xl rounded-xl bg-white p-6 shadow-sm"><h2 class="text-lg font-semibold">Abrir caja</h2><p class="mt-1 text-sm text-slate-500">Ingresa el monto inicial de efectivo.</p>@can('open', \App\Models\CashSession::class)<form wire:submit="openSession" class="mt-5"><x-input-label for="opening-amount" value="Monto inicial" /><x-text-input id="opening-amount" wire:model="openingAmount" type="number" min="0" step="0.01" class="mt-1 block w-full" /><x-input-error :messages="$errors->get('openingAmount')" class="mt-2" /><x-primary-button class="mt-4">Abrir caja</x-primary-button></form>@else<p class="mt-4 text-sm text-rose-600">No tienes permiso para abrir caja.</p>@endcan</div>
    @else
        @php($typeLabels = ['income' => 'Ingresos', 'expense' => 'Egresos', 'sale' => 'Ventas contado', 'credit_payment' => 'Cobros de crédito'])
        <div class="grid gap-4 md:grid-cols-4"><div class="rounded-xl bg-white p-4 shadow-sm"><div class="text-xs uppercase text-slate-500">Monto inicial</div><div class="mt-1 text-xl font-bold">{{ number_format((float) $session->opening_amount, 2) }}</div></div><div class="rounded-xl bg-white p-4 shadow-sm"><div class="text-xs uppercase text-slate-500">Efectivo esperado</div><div class="mt-1 text-xl font-bold text-emerald-700">{{ number_format((float) $expected, 2) }}</div></div>@foreach($methods as $method => $total)<div class="rounded-xl bg-white p-4 shadow-sm"><div class="text-xs uppercase text-slate-500">{{ ['cash' => 'Efectivo', 'qr' => 'QR', 'transfer' => 'Transferencia'][$method] }}</div><div class="mt-1 text-xl font-bold">{{ number_format((float) $total, 2) }}</div></div>@endforeach</div>
        <div class="mt-6 grid gap-6 lg:grid-cols-2"><div class="rounded-xl bg-white p-5 shadow-sm"><h2 class="font-semibold">Ingreso</h2><form wire:submit="registerIncome" class="mt-4 space-y-3"><x-text-input wire:model="incomeAmount" type="number" min="0.01" step="0.01" placeholder="Monto" class="w-full" /><select wire:model.live="incomeMethod" class="w-full rounded-md border-slate-300"><option value="cash">Efectivo</option><option value="qr">QR</option><option value="transfer">Transferencia</option></select><select wire:model="incomeAccountId" class="w-full rounded-md border-slate-300"><option value="">Cuenta receptora (si aplica)</option>@foreach($accounts as $account)<option value="{{ $account->id }}">{{ $account->name }} · {{ $account->type }}</option>@endforeach</select><x-text-input wire:model="incomeDescription" placeholder="Descripción" class="w-full" /><x-input-error :messages="$errors->get('incomeAmount')" /><x-input-error :messages="$errors->get('incomeAccountId')" /><x-primary-button>Registrar ingreso</x-primary-button></form></div><div class="rounded-xl bg-white p-5 shadow-sm"><h2 class="font-semibold">Egreso</h2><form wire:submit="registerExpense" class="mt-4 space-y-3"><x-text-input wire:model="expenseAmount" type="number" min="0.01" step="0.01" placeholder="Monto" class="w-full" /><select wire:model.live="expenseMethod" class="w-full rounded-md border-slate-300"><option value="cash">Efectivo</option><option value="qr">QR</option><option value="transfer">Transferencia</option></select><select wire:model="expenseAccountId" class="w-full rounded-md border-slate-300"><option value="">Cuenta receptora (si aplica)</option>@foreach($accounts as $account)<option value="{{ $account->id }}">{{ $account->name }} · {{ $account->type }}</option>@endforeach</select><x-text-input wire:model="expenseDescription" placeholder="Descripción" class="w-full" /><x-input-error :messages="$errors->get('expenseAmount')" /><x-input-error :messages="$errors->get('expenseAccountId')" /><x-primary-button>Registrar egreso</x-primary-button></form></div></div>
        <div class="mt-6 rounded-xl bg-white p-5 shadow-sm"><h2 class="font-semibold">Cierre y arqueo</h2><p class="mt-1 text-sm text-slate-500">El esperado de efectivo es {{ number_format((float) $expected, 2) }}.</p>@can('close', $session)<form wire:submit="closeSession" class="mt-4 flex max-w-xl gap-3"><x-text-input wire:model="countedAmount" type="number" min="0" step="0.01" placeholder="Monto contado" class="flex-1" /><x-primary-button>Cerrar caja</x-primary-button></form><x-input-error :messages="$errors->get('countedAmount')" class="mt-2" />@endcan</div>
    @endif
</div>
