<div>
    <div class="mb-6 flex items-center justify-between">
        <div><h1 class="text-2xl font-bold text-slate-900">{{ $title }}</h1><p class="text-sm text-slate-500">Administra el catálogo operativo.</p></div>
        @can('create', $this->policyClass()) <button wire:click="create" class="rounded-lg bg-indigo-600 px-4 py-2 text-sm font-semibold text-white hover:bg-indigo-700">Nuevo {{ $singular }}</button>@endcan
    </div>
    <div class="rounded-xl bg-white p-5 shadow-sm">
        <x-table-toolbar wire:model.live.debounce.300ms="search" />
        <div class="mt-5 overflow-x-auto">
            <table class="w-full text-left text-sm"><thead class="border-b text-xs uppercase text-slate-500"><tr><th class="px-3 py-3">Nombre</th><th class="px-3 py-3">Estado</th><th class="px-3 py-3 text-right">Acciones</th></tr></thead>
                <tbody class="divide-y divide-slate-100">@forelse($records as $record)<tr><td class="px-3 py-3 font-medium">{{ $record->name }}@if($type === 'attributes')<div class="mt-2 flex flex-wrap gap-1">@foreach($record->values as $item)<span class="rounded bg-slate-100 px-2 py-1 text-xs text-slate-600">{{ $item->value }}</span>@endforeach</div><div class="mt-2 flex gap-2"><input wire:model="newValue" placeholder="Nuevo valor" class="rounded border-slate-300 text-xs"><button wire:click="addValue({{ $record->id }})" class="text-xs font-semibold text-indigo-600">Agregar valor</button></div>@endif</td><td class="px-3 py-3"><span class="rounded-full px-2 py-1 text-xs {{ ($record->is_active ?? true) ? 'bg-emerald-100 text-emerald-700' : 'bg-slate-100 text-slate-500' }}">{{ ($record->is_active ?? true) ? 'Activo' : 'Inactivo' }}</span></td><td class="px-3 py-3 text-right"><button wire:click="edit({{ $record->id }})" class="text-indigo-600">Editar</button><button wire:click="delete({{ $record->id }})" wire:confirm="¿Eliminar este registro?" class="ml-3 text-rose-600">Eliminar</button></td></tr>@empty<tr><td colspan="3" class="px-3 py-12 text-center text-slate-500">No hay registros.</td></tr>@endforelse</tbody>
            </table>
        </div>
        <div class="mt-4">{{ $records->links() }}</div>
    </div>
    <x-modal name="catalog-record" wire:model="showModal"><div class="p-6"><h2 class="text-lg font-semibold">{{ $editingId ? 'Editar' : 'Nuevo' }} {{ $singular }}</h2><div class="mt-4 space-y-4"><div><x-input-label value="Nombre"/><x-text-input wire:model="name" class="mt-1 w-full"/><x-input-error :messages="$errors->get('name')" /></div>@if($type === 'categories')<div><x-input-label value="Categoría padre"/><select wire:model="parentId" class="mt-1 w-full rounded-lg border-slate-300"><option value="">Sin padre</option>@foreach($parents as $parent)<option value="{{ $parent->id }}">{{ $parent->name }}</option>@endforeach</select></div>@endif@if($type === 'units')<div><x-input-label value="Abreviatura"/><x-text-input wire:model="abbreviation" class="mt-1 w-full"/></div>@endif<div><label class="flex items-center gap-2"><input type="checkbox" wire:model="isActive" class="rounded border-slate-300 text-indigo-600"> Activo</label></div>@if($type === 'locations')<div><label class="flex items-center gap-2"><input type="checkbox" wire:model="isDefault" class="rounded border-slate-300 text-indigo-600"> Ubicación predeterminada</label></div>@endif</div><div class="mt-6 flex justify-end gap-3"><button wire:click="$set('showModal', false)" class="rounded-lg border px-4 py-2">Cancelar</button><button wire:click="save" class="rounded-lg bg-indigo-600 px-4 py-2 text-white">Guardar</button></div></div></x-modal>
</div>
