<div>
    <div class="mb-6"><h1 class="text-2xl font-bold text-slate-900">Panel ejecutivo</h1><p class="text-sm text-slate-500">Resumen operativo de {{ app(\App\Support\CompanySettings::class)->name() }}.</p></div>
    <div class="grid gap-4 md:grid-cols-2 lg:grid-cols-4">
        @can('viewAny', \App\Models\Sale::class)<div class="rounded-xl bg-white p-5 shadow-sm"><div class="text-xs uppercase text-slate-500">Ventas del día</div><div class="mt-2 text-2xl font-bold text-indigo-700">{{ money($salesToday) }}</div><div class="text-xs text-slate-500">{{ $salesCountToday }} operaciones</div></div>@endcan
        @can('viewAny', \App\Models\Purchase::class)<div class="rounded-xl bg-white p-5 shadow-sm"><div class="text-xs uppercase text-slate-500">Compras del día</div><div class="mt-2 text-2xl font-bold">{{ money($purchasesToday) }}</div></div>@endcan
        @can('viewAny', \App\Models\CashSession::class)<div class="rounded-xl bg-white p-5 shadow-sm"><div class="text-xs uppercase text-slate-500">Caja</div><div class="mt-2 text-xl font-bold">{{ $openSession ? 'Abierta' : 'Cerrada' }}</div><div class="text-xs text-slate-500">Efectivo esperado: {{ money((float) $expectedCash) }}</div></div>@endcan
        @can('viewAny', \App\Models\Credit::class)<div class="rounded-xl bg-white p-5 shadow-sm"><div class="text-xs uppercase text-slate-500">Créditos pendientes</div><div class="mt-2 text-2xl font-bold text-rose-700">{{ money($creditsBalance) }}</div><div class="text-xs text-slate-500">{{ $overdueCredits }} vencidos</div></div>@endcan
    </div>
    <div class="mt-6 grid gap-6 lg:grid-cols-2">
        @can('viewAny', \App\Models\Credit::class)<div class="rounded-xl bg-white p-5 shadow-sm"><h2 class="font-semibold">Alertas de vencimiento</h2><div class="mt-4 grid gap-3 sm:grid-cols-3 text-sm"><div class="rounded-lg bg-amber-50 p-3 text-amber-800"><div>Próximos a vencer</div><strong>{{ $upcomingCount }} · {{ money($upcomingAmount) }}</strong></div><div class="rounded-lg bg-orange-50 p-3 text-orange-800"><div>Vencen hoy</div><strong>{{ $dueTodayCount }} · {{ money($dueTodayAmount) }}</strong></div><div class="rounded-lg bg-rose-50 p-3 text-rose-800"><div>Vencidos</div><strong>{{ $overdueCount }} · {{ money($overdueAmount) }}</strong></div></div><div class="mt-4 space-y-2">@forelse($delinquentCustomers as $item)<div class="flex justify-between text-sm"><span>{{ $item['customer']?->name }}</span><span class="font-medium text-rose-700">{{ $item['days_overdue'] }} días · {{ money($item['balance']) }}</span></div>@empty<p class="text-sm text-slate-500">No hay clientes con mora.</p>@endforelse</div></div>@endcan
        @can('viewAny', \App\Models\Inventory::class)<div class="rounded-xl bg-white p-5 shadow-sm"><div class="flex justify-between"><h2 class="font-semibold">Productos con bajo stock</h2><span class="text-sm text-rose-600">{{ $lowStockCount }}</span></div><div class="mt-4 space-y-3">@forelse($lowStock as $item)<div class="flex justify-between text-sm"><span>{{ $item->product?->name }} <span class="text-slate-400">· {{ $item->location?->name }}</span></span><strong class="text-rose-600">{{ qty($item->quantity) }}</strong></div>@empty<p class="text-sm text-slate-500">No hay alertas de bajo stock.</p>@endforelse</div></div>@endcan
        @can('viewAny', \App\Models\Sale::class)<div class="rounded-xl bg-white p-5 shadow-sm"><h2 class="font-semibold">Productos más vendidos (30 días)</h2><div class="mt-4 space-y-3">@forelse($bestSelling as $item)<div class="flex justify-between text-sm"><span>{{ $item->product?->name }}</span><strong>{{ qty($item->quantity) }}</strong></div>@empty<p class="text-sm text-slate-500">No hay ventas recientes.</p>@endforelse</div></div>@endcan
    </div>
    <div class="mt-6 grid gap-6 lg:grid-cols-2">
        @can('viewAny', \App\Models\Credit::class)<div class="rounded-xl bg-white p-5 shadow-sm"><h2 class="font-semibold">Alertas importantes</h2><div class="mt-4 space-y-2 text-sm">@forelse($dueCredits as $credit)<div class="text-amber-700">Crédito de {{ $credit->customer?->name }} por vencer el {{ $credit->due_date?->format('d/m/Y') }}</div>@empty<span class="text-slate-500">No hay créditos próximos a vencer.</span>@endforelse @foreach($cashDifferences as $session)<div class="text-rose-700">Diferencia de arqueo: {{ money((float) $session->difference) }}</div>@endforeach</div></div>@endcan
        @can('viewAny', \App\Models\CashSession::class)<div class="rounded-xl bg-white p-5 shadow-sm"><h2 class="font-semibold">Últimos movimientos de caja</h2><div class="mt-4 space-y-3">@forelse($recentMovements as $movement)<div class="flex justify-between text-sm"><span>{{ $movement->type->label() }} · {{ $movement->created_at?->format('d/m H:i') }}</span><strong>{{ money((float) $movement->amount) }}</strong></div>@empty<p class="text-sm text-slate-500">No hay movimientos recientes.</p>@endforelse</div></div>@endcan
    </div>
</div>
