<div>
    <div class="mb-6"><h1 class="text-2xl font-bold text-slate-900">Panel ejecutivo</h1><p class="text-sm text-slate-500">Resumen operativo de Construir a tu Alcance.</p></div>
    <div class="grid gap-4 md:grid-cols-2 lg:grid-cols-4">
        @can('viewAny', \App\Models\Sale::class)<div class="rounded-xl bg-white p-5 shadow-sm"><div class="text-xs uppercase text-slate-500">Ventas del día</div><div class="mt-2 text-2xl font-bold text-indigo-700">{{ number_format($salesToday, 2) }}</div><div class="text-xs text-slate-500">{{ $salesCountToday }} operaciones</div></div>@endcan
        @can('viewAny', \App\Models\Purchase::class)<div class="rounded-xl bg-white p-5 shadow-sm"><div class="text-xs uppercase text-slate-500">Compras del día</div><div class="mt-2 text-2xl font-bold">{{ number_format($purchasesToday, 2) }}</div></div>@endcan
        @can('viewAny', \App\Models\CashSession::class)<div class="rounded-xl bg-white p-5 shadow-sm"><div class="text-xs uppercase text-slate-500">Caja</div><div class="mt-2 text-xl font-bold">{{ $openSession ? 'Abierta' : 'Cerrada' }}</div><div class="text-xs text-slate-500">Efectivo esperado: {{ number_format((float) $expectedCash, 2) }}</div></div>@endcan
        @can('viewAny', \App\Models\Credit::class)<div class="rounded-xl bg-white p-5 shadow-sm"><div class="text-xs uppercase text-slate-500">Créditos pendientes</div><div class="mt-2 text-2xl font-bold text-rose-700">{{ number_format($creditsBalance, 2) }}</div><div class="text-xs text-slate-500">{{ $overdueCredits }} vencidos</div></div>@endcan
    </div>
    <div class="mt-6 grid gap-6 lg:grid-cols-2">
        @can('viewAny', \App\Models\Inventory::class)<div class="rounded-xl bg-white p-5 shadow-sm"><div class="flex justify-between"><h2 class="font-semibold">Productos con bajo stock</h2><span class="text-sm text-rose-600">{{ $lowStockCount }}</span></div><div class="mt-4 space-y-3">@forelse($lowStock as $item)<div class="flex justify-between text-sm"><span>{{ $item->product?->name }} <span class="text-slate-400">· {{ $item->location?->name }}</span></span><strong class="text-rose-600">{{ $item->quantity }}</strong></div>@empty<p class="text-sm text-slate-500">No hay alertas de bajo stock.</p>@endforelse</div></div>@endcan
        @can('viewAny', \App\Models\Sale::class)<div class="rounded-xl bg-white p-5 shadow-sm"><h2 class="font-semibold">Productos más vendidos (30 días)</h2><div class="mt-4 space-y-3">@forelse($bestSelling as $item)<div class="flex justify-between text-sm"><span>{{ $item->product?->name }}</span><strong>{{ $item->quantity }}</strong></div>@empty<p class="text-sm text-slate-500">No hay ventas recientes.</p>@endforelse</div></div>@endcan
    </div>
    <div class="mt-6 grid gap-6 lg:grid-cols-2">
        @can('viewAny', \App\Models\Credit::class)<div class="rounded-xl bg-white p-5 shadow-sm"><h2 class="font-semibold">Alertas importantes</h2><div class="mt-4 space-y-2 text-sm">@forelse($dueCredits as $credit)<div class="text-amber-700">Crédito de {{ $credit->customer?->name }} por vencer el {{ $credit->due_date?->format('d/m/Y') }}</div>@empty<span class="text-slate-500">No hay créditos próximos a vencer.</span>@endforelse @foreach($cashDifferences as $session)<div class="text-rose-700">Diferencia de arqueo: {{ number_format((float) $session->difference, 2) }}</div>@endforeach</div></div>@endcan
        @can('viewAny', \App\Models\CashSession::class)<div class="rounded-xl bg-white p-5 shadow-sm"><h2 class="font-semibold">Últimos movimientos de caja</h2><div class="mt-4 space-y-3">@forelse($recentMovements as $movement)<div class="flex justify-between text-sm"><span>{{ $movement->type->value }} · {{ $movement->created_at?->format('d/m H:i') }}</span><strong>{{ number_format((float) $movement->amount, 2) }}</strong></div>@empty<p class="text-sm text-slate-500">No hay movimientos recientes.</p>@endforelse</div></div>@endcan
    </div>
</div>
