<div>
    <div class="mb-6 flex items-center justify-between"><div><a href="{{ route('products.index') }}" class="text-sm text-indigo-600">← Productos</a><h1 class="mt-2 text-2xl font-bold text-slate-900">{{ $product ? 'Editar producto' : 'Nuevo producto' }}</h1></div><button wire:click="save" wire:loading.attr="disabled" class="rounded-lg bg-indigo-600 px-5 py-2 text-sm font-semibold text-white">Guardar producto</button></div>
    @if(session('success'))<div class="mb-4 rounded-lg bg-emerald-50 p-3 text-sm text-emerald-700">{{ session('success') }}</div>@endif
    <div class="grid gap-6 lg:grid-cols-3">
        <section class="space-y-6 lg:col-span-2">
            <div class="rounded-xl bg-white p-6 shadow-sm"><h2 class="font-semibold text-slate-900">Información general</h2><div class="mt-4 grid gap-4 sm:grid-cols-2"><div class="sm:col-span-2"><x-input-label value="Nombre"/><x-text-input wire:model="name" class="mt-1 w-full"/><x-input-error :messages="$errors->get('name')" /></div><div><x-input-label value="Código"/><x-text-input wire:model="code" class="mt-1 w-full" placeholder="Automático si queda vacío"/><x-input-error :messages="$errors->get('code')" /></div><div><x-input-label value="Código de barras"/><x-text-input wire:model="barcode" class="mt-1 w-full"/></div><div><x-input-label value="Categoría"/><select wire:model="categoryId" class="mt-1 w-full rounded-lg border-slate-300"><option value="">Seleccionar</option>@foreach($categories as $category)<option value="{{ $category->id }}">{{ $category->name }}</option>@endforeach</select></div><div><x-input-label value="Marca"/><select wire:model="brandId" class="mt-1 w-full rounded-lg border-slate-300"><option value="">Seleccionar</option>@foreach($brands as $brand)<option value="{{ $brand->id }}">{{ $brand->name }}</option>@endforeach</select></div><div><x-input-label value="Unidad base"/><select wire:model="unitId" class="mt-1 w-full rounded-lg border-slate-300"><option value="">Seleccionar</option>@foreach($units as $unit)<option value="{{ $unit->id }}">{{ $unit->name }} ({{ $unit->abbreviation }})</option>@endforeach</select></div><div><x-input-label value="Stock mínimo"/><x-text-input type="number" step="0.0001" wire:model="minStock" class="mt-1 w-full"/></div><div class="sm:col-span-2"><x-input-label value="Descripción"/><textarea wire:model="description" rows="3" class="mt-1 w-full rounded-lg border-slate-300"></textarea></div><label class="flex items-center gap-2 text-sm"><input type="checkbox" wire:model="isActive" class="rounded border-slate-300 text-indigo-600"> Producto activo</label></div></div>
            <div class="rounded-xl bg-white p-6 shadow-sm"><div class="flex items-center justify-between"><h2 class="font-semibold">Presentaciones</h2><button wire:click="addPresentation" class="text-sm font-semibold text-indigo-600">+ Agregar</button></div><div class="mt-4 space-y-3">@foreach($presentations as $index => $presentation)<div class="grid gap-2 rounded-lg bg-slate-50 p-3 sm:grid-cols-5" wire:key="presentation-{{ $index }}"><input wire:model="presentations.{{ $index }}.name" placeholder="Nombre" class="rounded border-slate-300 text-sm"><input type="number" step="0.0001" wire:model="presentations.{{ $index }}.equivalence" placeholder="Equivalencia" class="rounded border-slate-300 text-sm"><input type="number" step="0.01" wire:model="presentations.{{ $index }}.price_without_invoice" placeholder="Sin factura" class="rounded border-slate-300 text-sm"><input type="number" step="0.01" wire:model="presentations.{{ $index }}.price_with_invoice" placeholder="Con factura" class="rounded border-slate-300 text-sm"><button wire:click="removePresentation({{ $index }})" class="text-sm text-rose-600">Quitar</button></div>@endforeach</div></div>
            <div class="rounded-xl bg-white p-6 shadow-sm"><h2 class="font-semibold">Atributos y relacionados</h2><div class="mt-4 grid gap-5 sm:grid-cols-2"><div><x-input-label value="Valores de atributos"/><select multiple wire:model="attributeValueIds" class="mt-1 h-40 w-full rounded-lg border-slate-300">@foreach($attributeValues as $attributeValue)<option value="{{ $attributeValue->id }}">{{ $attributeValue->attribute->name }}: {{ $attributeValue->value }}</option>@endforeach</select></div><div><x-input-label value="Productos relacionados"/><select multiple wire:model="relatedProductIds" class="mt-1 h-40 w-full rounded-lg border-slate-300">@foreach($relatedProducts as $related)<option value="{{ $related->id }}">{{ $related->name }} ({{ $related->code }})</option>@endforeach</select><p class="mt-1 text-xs text-slate-500">Relación dirigida: se muestran los productos seleccionados desde este producto.</p></div></div></div>
        </section>
        <aside class="space-y-6"><div class="rounded-xl bg-white p-6 shadow-sm"><h2 class="font-semibold">Imágenes</h2><input type="file" wire:model="images" multiple accept="image/*" class="mt-4 block w-full text-sm"><div wire:loading wire:target="images" class="mt-2 text-sm text-slate-500">Subiendo...</div><div class="mt-4 grid grid-cols-2 gap-3">@foreach($existingImages as $index => $image)<div class="relative"><img src="{{ Storage::disk($image['disk'])->url($image['path']) }}" class="h-28 w-full rounded-lg object-cover"><button wire:click="removeImage({{ $index }})" class="absolute right-1 top-1 rounded bg-rose-600 px-2 py-1 text-xs text-white">×</button></div>@endforeach @foreach($images as $image)<div><img src="{{ $image->temporaryUrl() }}" class="h-28 w-full rounded-lg object-cover"></div>@endforeach</div><x-input-error :messages="$errors->get('images.*')" /></div><div class="rounded-xl bg-white p-6 shadow-sm"><h2 class="font-semibold">Costo promedio</h2><p class="mt-1 text-xs text-slate-500">El costo se recalcula al recibir mercadería.</p><x-text-input type="number" step="0.0001" wire:model="cost" class="mt-3 w-full" /></div></aside>
    </div>
</div>
