<div>
    <div class="mb-6"><a href="{{ route('sales.index') }}" class="text-sm text-indigo-600">← Ventas</a><h1 class="mt-2 text-2xl font-bold text-slate-900">Nueva venta</h1></div>
    @if($errors->any())<div class="mb-4 rounded-lg bg-rose-50 p-3 text-sm text-rose-700"><ul class="list-disc pl-5">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
    <div class="grid gap-6 lg:grid-cols-3">
        <section class="space-y-6 lg:col-span-2">
            <div class="rounded-xl bg-white p-6 shadow-sm">
                <div class="flex items-center justify-between"><h2 class="font-semibold">Datos de la venta</h2><label class="flex items-center gap-2 text-sm"><input type="checkbox" wire:model.live="withInvoice" class="rounded border-slate-300 text-indigo-600"> Venta con factura</label></div>
                <div class="mt-4 grid gap-4 sm:grid-cols-2">
                    <div><x-input-label value="Ubicación de salida"/><select wire:model.live="locationId" class="mt-1 w-full rounded-lg border-slate-300"><option value="">Seleccionar</option>@foreach($locations as $location)<option value="{{ $location->id }}">{{ $location->name }}</option>@endforeach</select><x-input-error :messages="$errors->get('locationId')"/></div>
                    <div><x-input-label value="Tipo de pago"/><select wire:model.live="paymentType" class="mt-1 w-full rounded-lg border-slate-300"><option value="cash">Contado</option><option value="credit">Crédito</option><option value="mixed">Mixto</option></select></div>
                    <div><x-input-label value="Medio de pago contado"/><select wire:model="paymentMethod" class="mt-1 w-full rounded-lg border-slate-300"><option value="cash">Efectivo</option><option value="qr">QR</option><option value="transfer">Transferencia</option></select></div>
                    <div><x-input-label value="Cliente"/><div class="flex gap-2"><select wire:model="customerId" class="mt-1 w-full rounded-lg border-slate-300"><option value="">Cliente ocasional</option>@foreach($customers as $customer)<option value="{{ $customer->id }}">{{ $customer->name }}{{ $customer->document_number ? ' · '.$customer->document_number : '' }}</option>@endforeach</select>@can('create', \App\Models\Customer::class)<button type="button" wire:click="$dispatch('customer-form-open')" class="mt-1 whitespace-nowrap rounded-lg border px-3 text-sm">Nuevo cliente</button>@endcan</div><x-input-error :messages="$errors->get('customerId')"/></div>
                </div>
                <div class="mt-4"><x-text-input wire:model.live.debounce.300ms="customerSearch" class="w-full" placeholder="Buscar cliente por nombre, documento o teléfono..."/></div>
            </div>
            <div class="rounded-xl bg-white p-6 shadow-sm">
                <h2 class="font-semibold">Productos</h2>
                <div class="relative mt-4"><x-text-input wire:model.live.debounce.300ms="productSearch" class="w-full" placeholder="Buscar por nombre, código, barra, marca o atributo..."/>@if($productSearch !== '')<div class="absolute z-10 mt-1 w-full rounded-lg border bg-white shadow">@forelse($products as $product)<button type="button" wire:click="selectProduct({{ $product->id }})" class="block w-full px-4 py-2 text-left text-sm hover:bg-slate-50">{{ $product->name }} ({{ $product->code }})@if($product->presentations->first()) · {{ $product->presentations->first()->name }}@endif</button>@empty<div class="p-3 text-sm text-slate-500">No se encontraron productos.</div>@endforelse</div>@endif</div>
                <div class="mt-5 space-y-3">@forelse($items as $index => $item)<div wire:key="sale-item-{{ $index }}" class="grid gap-2 rounded-lg bg-slate-50 p-3 sm:grid-cols-12"><div class="sm:col-span-4"><div class="font-medium text-sm">{{ $products->firstWhere('id', $item['product_id'])?->name ?? \App\Models\Product::find($item['product_id'])?->name }}</div><select wire:model.live="items.{{ $index }}.presentation_id" class="mt-1 w-full rounded border-slate-300 text-xs"><option value="">Presentación</option>@foreach(\App\Models\Product::find($item['product_id'])?->presentations ?? [] as $presentation)<option value="{{ $presentation->id }}">{{ $presentation->name }} · {{ $withInvoice ? $presentation->price_with_invoice : $presentation->price_without_invoice }}</option>@endforeach</select></div><input wire:model.live="items.{{ $index }}.quantity" type="number" min="0.0001" step="0.0001" class="rounded border-slate-300 text-sm sm:col-span-2" placeholder="Cantidad"><div class="py-2 text-xs text-slate-600 sm:col-span-2">Stock: {{ number_format((float) ($lineStocks[$index] ?? 0), 4) }} presentaciones</div><input wire:model.live="items.{{ $index }}.unit_price" type="number" min="0" step="0.01" class="rounded border-slate-300 text-sm sm:col-span-2" placeholder="Precio"><div class="py-2 text-sm font-semibold sm:col-span-1">{{ number_format((float) ($item['subtotal'] ?? 0), 2) }}</div><button type="button" wire:click="removeItem({{ $index }})" class="text-sm text-rose-600 sm:col-span-1">Quitar</button>@if((float) ($item['quantity'] ?? 0) > (float) ($lineStocks[$index] ?? 0))<div class="sm:col-span-12 text-xs font-medium text-rose-600">Advertencia: la cantidad supera el stock disponible.</div>@endif</div>@empty<div class="py-10 text-center text-sm text-slate-500">Busca un producto para agregarlo.</div>@endforelse</div>
            </div>
        </section>
        <aside class="rounded-xl bg-white p-6 shadow-sm"><h2 class="font-semibold">Resumen</h2><div class="mt-5"><x-input-label value="Descuento"/><x-text-input wire:model.live="discount" type="number" min="0" step="0.01" class="mt-1 w-full"/><x-input-error :messages="$errors->get('discount')"/></div><div class="mt-6 space-y-2 border-t pt-4 text-sm"><div class="flex justify-between"><span>Subtotal</span><span>{{ number_format((float) collect($items)->sum('subtotal'), 2) }}</span></div><div class="flex justify-between"><span>Descuento</span><span>{{ number_format((float) $discount, 2) }}</span></div><div class="flex justify-between text-lg font-bold"><span>Total</span><span>{{ number_format(max(0, (float) collect($items)->sum('subtotal') - (float) $discount), 2) }}</span></div></div><button type="button" wire:click="save" class="mt-6 w-full rounded-lg bg-indigo-600 px-5 py-3 text-sm font-semibold text-white">Confirmar venta</button></aside>
    </div>
    @can('create', \App\Models\Customer::class)<livewire:customer-form :in-modal="true" />@endcan
</div>
